### ISSUE TITLE
Drop object-pascal implementation

### ISSUE THREAD

**Issue by mememori** [mabrasil/safadometro#47]
It does not follows the folder standard, it includes local data and includes binaries and thus should be removed until fixed

**Comment by haskellcamargo** [comment]
+1. Check it, @mabrasil.

**Comment by mememori** [comment]
Related: PRs #33 and #43

**Comment by haskellcamargo** [comment]
Done.

**Comment by mabrasil** [comment]
I see your point @mememori and thanx @haskellcamargo for doing it.
