### ISSUE TITLE
Restriction to implement the algorithm

### ISSUE THREAD

**Issue by jrdalpra** [mabrasil/safadometro#7]
Everyone that implements this algorithm must do it if and only if is listening the music.

**Comment by ramirio** [comment]
:+1:

**Comment by marcelodeveloper** [comment]
Go Safadão!

**Comment by NatanJMai** [comment]
Sorry, but I was not listening the music :(

**Comment by haskellcamargo** [comment]
Shame!

**Comment by jrdalpra** [comment]
Shame! This must be at README.

On Tuesday, December 15, 2015, Marcelo Camargo <notifications@github.com>
wrote:

> Shame!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mabrasil/safadometro/issues/7#issuecomment-164912824>.
>


-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com
